# Generated by Django 4.2.28 on 2026-03-05 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_incident_support_rescue_publicsnapshot_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('terrain_path', models.CharField(blank=True, help_text='Path to extracted heightfield', max_length=512)),
                ('buildings_path', models.CharField(blank=True, help_text='Path to extracted OSM/PLATEAU buildings', max_length=512)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Metadata about the source extractions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Simulation Area', max_length=255)),
                ('bbox_min_lat', models.FloatField()),
                ('bbox_min_lng', models.FloatField()),
                ('bbox_max_lat', models.FloatField()),
                ('bbox_max_lng', models.FloatField()),
                ('polygon_geometry', models.JSONField(blank=True, default=dict, help_text='Optional complex geometry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('water_level_start', models.FloatField(default=0.0)),
                ('rainfall_mm', models.FloatField(default=50.0)),
                ('duration_hours', models.FloatField(default=24.0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Flooded area, volume, building intersections')),
                ('artifacts', models.JSONField(blank=True, default=dict, help_text='Paths to output textures or GeoJSON layers')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.scenariobundle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scenariobundle',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.simulationarea'),
        ),
    ]
