# Generated by Django 4.2.28 on 2026-03-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scenariobundle_simulationarea_simulationrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_user_id', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EdgeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('local_ip', models.GenericIPAddressField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='online', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='attentionalert',
            new_name='api_attenti_created_31f8e5_idx',
            old_name='apps_api_at_created_f3ee4f_idx',
        ),
        migrations.RenameIndex(
            model_name='attentionalert',
            new_name='api_attenti_severit_140c56_idx',
            old_name='apps_api_at_severit_e7c064_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_entity__ad4253_idx',
            old_name='api_auditlo_entity__3fcd0c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_timesta_96ac8f_idx',
            old_name='api_auditlo_timesta_2a3e8f_idx',
        ),
        migrations.RenameIndex(
            model_name='collapsereport',
            new_name='api_collaps_created_74d0c8_idx',
            old_name='apps_api_co_created_033f32_idx',
        ),
        migrations.RenameIndex(
            model_name='disasterevent',
            new_name='api_disaste_country_fa3a22_idx',
            old_name='api_disaste_country_44e9fd_idx',
        ),
        migrations.RenameIndex(
            model_name='disasterevent',
            new_name='api_disaste_start_a_cfb740_idx',
            old_name='api_disaste_start_a_a68f71_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='api_inciden_status_76b4f2_idx',
            old_name='api_inciden_status_34b0d6_idx',
        ),
        migrations.RenameIndex(
            model_name='mapannotation',
            new_name='api_mapanno_record__f06893_idx',
            old_name='api_mapanno_record__8d60f0_idx',
        ),
        migrations.RenameIndex(
            model_name='mapannotation',
            new_name='api_mapanno_status_a2e0fa_idx',
            old_name='api_mapanno_status_28d443_idx',
        ),
        migrations.RenameIndex(
            model_name='missingperson',
            new_name='api_missing_created_df84fe_idx',
            old_name='apps_api_mi_created_8c0ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='missingperson',
            new_name='api_missing_city_18cc06_idx',
            old_name='apps_api_mi_city_4b9c99_idx',
        ),
        migrations.RenameIndex(
            model_name='publicsnapshot',
            new_name='api_publics_inciden_c548f3_idx',
            old_name='api_publics_inciden_67ecf3_idx',
        ),
        migrations.AddField(
            model_name='assignment',
            name='external_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='external_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donationmoney',
            name='external_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='external_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='searcharea',
            name='external_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='event_type',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Cyclone', 'Cyclone'), ('Volcano', 'Volcano'), ('Wildfire', 'Wildfire'), ('Storm', 'Storm'), ('Tsunami', 'Tsunami'), ('Landslide', 'Landslide'), ('Conflict', 'Conflict'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='processedcommand',
            index=models.Index(fields=['command_id'], name='api_process_command_036289_idx'),
        ),
        migrations.AddField(
            model_name='edgehub',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.incident'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_id', 'aggregate_type'], name='api_domaine_aggrega_0e016e_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['-timestamp'], name='api_domaine_timesta_508987_idx'),
        ),
        migrations.AddIndex(
            model_name='edgehub',
            index=models.Index(fields=['hub_id'], name='api_edgehub_hub_id_8207f8_idx'),
        ),
        migrations.AddIndex(
            model_name='edgehub',
            index=models.Index(fields=['incident'], name='api_edgehub_inciden_96c3b4_idx'),
        ),
    ]
